### ISSUE TITLE
Suggestion to expose port 8889

### ISSUE THREAD

**Issue by Firsh** [MyUncleSam/docker-syncovery#3]
When adding Google Drive (perhaps any other cloud service that needs auth) the redirect URL contains 8889. This address is used only briefly and one time, when letting the connection happen in the first place. Unless that's exposed as well, we can't add the remote service.

By the way, thanks for creating this image, I really like Syncovery on Win, and now I have a way to performantly back up my data within WSL/Docker, those files that are not supposed to end up in a repo. Without your help the dockerization would have taken way longer for me.

**Comment by sqldiablo** [comment]
I'm having the same issue. When I try to authenticate Google Drive, it wants to use port 8889, which isn't exposed by this dockerfile, and so I can't complete authentication.

**Comment by MyUncleSam** [comment]
expose for port 8889 added, hope this helps (sorry for the late response but it seemed like I do not get any notifications for new issues)
