### ISSUE TITLE
Document the build process

### ISSUE THREAD

**Issue by barbudor** [MyUncleSam/docker-syncovery#4]
Thanks a lot for that

It would be nice to better document the build process or may be include a scripts which does the parsing of the listed URL and call the docker build accordingly.
Here below is the dirty script I quickly made, doesn't include any error check but it did allowed me to build successfully the docker image locally. I could provide a PR but not sure you would find this clean enough to be included.

Once again thank you for providing this.

All best

```bash
#!/usr/bin/env bash

wget https://www.syncovery.com/linver_x86_64-Web.tar.gz.txt 2>/dev/null
wget https://www.syncovery.com/linver_guardian_x86_64.tar.gz.txt 2>/dev/null
wget https://www.syncovery.com/linver_rs_x86_64.tar.gz.txt 2>/dev/null

mapfile -t syncovery <linver_x86_64-Web.tar.gz.txt
mapfile -t guardian  <linver_guardian_x86_64.tar.gz.txt
mapfile -t remote    <linver_rs_x86_64.tar.gz.txt

SYNCOVERY_DOWNLOADLINK=${syncovery[2]}
VERSION=${syncovery[4]}
GUARD_DOWNLOADLINK=${guardian[2]}
REMOTE_DOWNLOADLINK=${remote[2]}

docker build . -t docker_syncovery:${VERSION}-ubuntu \
  --build-arg SYNCOVERY_DOWNLOADLINK=${SYNCOVERY_DOWNLOADLINK} \
  --build-arg GUARD_DOWNLOADLINK=${GUARD_DOWNLOADLINK} \
  --build-arg REMOTE_DOWNLOADLINK=${REMOTE_DOWNLOADLINK}
```

**Comment by jeanmichel-nwsb** [comment]
PR for the build script: https://github.com/MyUncleSam/docker-syncovery/pull/5

**Comment by MyUncleSam** [comment]
I was not seeing the PR and revoked it as I completely changed the source code which included a Jenkinsfile with all build instructions, also the scripts got moved to the repo which makes it now 100% clear how the build process is done (sorry for the late response but it seemed like I do not get any notifications for new issues)
